// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

var (
	Type = component.MustNewType("dynatrace")
)

<<<<<<<< HEAD:exporter/dynatraceexporter/internal/metadata/generated_status.go
const (
	MetricsStability = component.StabilityLevelDeprecated
========
var (
	Type = component.MustNewType("namedpipe")
)

const (
	LogsStability = component.StabilityLevelAlpha
>>>>>>>> opentelemetry-collector-contrib/release/0.100.x:receiver/namedpipereceiver/internal/metadata/generated_status.go
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("otelcol/dynatrace")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("otelcol/dynatrace")
}
