// Code generated by mdatagen. DO NOT EDIT.

<<<<<<<< HEAD:connector/signaltometricsconnector/generated_package_test.go
package signaltometricsconnector
|||||||| 6b1d3dd2c0c:exporter/instanaexporter/generated_package_test.go
package instanaexporter
========
package sumconnector
>>>>>>>> v0.137.0:connector/sumconnector/generated_package_test.go

import (
	"testing"

	"go.uber.org/goleak"
)

func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m)
}
