// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
<<<<<<<< HEAD:receiver/systemdreceiver/internal/metadata/generated_status.go
	Type      = component.MustNewType("systemd")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/systemdreceiver"
|||||||| 6b1d3dd2c0c:receiver/gitproviderreceiver/internal/metadata/generated_status.go
	Type = component.MustNewType("gitprovider")
========
	Type      = component.MustNewType("ciscoosreceiver")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/ciscoosreceiver"
>>>>>>>> v0.137.0:receiver/ciscoosreceiver/internal/metadata/generated_status.go
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
