// Code generated by mdatagen. DO NOT EDIT.

<<<<<<<< HEAD:extension/cgroupruntimeextension/generated_package_test.go
package cgroupruntimeextension
|||||||| 6b1d3dd2c0c:receiver/gitproviderreceiver/generated_package_test.go
package gitproviderreceiver
========
package coralogixprocessor
>>>>>>>> v0.137.0:processor/coralogixprocessor/generated_package_test.go

import (
	"testing"

	"go.uber.org/goleak"
)

func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m)
}
