// Code generated by mdatagen. DO NOT EDIT.

<<<<<<<< HEAD:receiver/googlecloudmonitoringreceiver/generated_package_test.go
package googlecloudmonitoringreceiver
|||||||| 6b1d3dd2c0c:exporter/skywalkingexporter/generated_package_test.go
package skywalkingexporter
========
package azureblobexporter
>>>>>>>> v0.137.0:exporter/azureblobexporter/generated_package_test.go

import (
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	// skipping goleak test as per metadata.yml configuration
	os.Exit(m.Run())
}
